### ISSUE TITLE
Task1 - consume api. API not responding. Application error

### ISSUE THREAD

**Issue by bartosobczynski** [netguru-training/pairguru#3]
"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

**Comment by jkubacki** [comment]
Hi @bartosobczynski. Thank you for bringing it up. We'll try to resolve it soon. Cheers :)

**Comment by jkubacki** [comment]
Api is working fine now. Thanks again @bartosobczynski :)
